### ISSUE TITLE
Cannot pass all-in-one-mode assertion

### ISSUE THREAD

**Issue by jessequinn** [cloudalchemy/ansible-cortex#19]
**What happened?**

```
TASK [cloudalchemy.cortex : Services should be empty when all-in-one-mode is enabled] **************************************************************************************************************************************************
fatal: [cortex]: FAILED! => {
    "assertion": "cortex_all_in_one == (cortex_services|length == 0)",
    "changed": false,
    "evaluated_to": false,
    "msg": "Exactly one of cortex_all_in_one or cortex_services should be set."
}
```

**Did you expect to see some different?**

expected to pass assertion.

**How to reproduce it (as minimally and precisely as possible)**:

```
- hosts: all
   roles:
    - cloudalchemy.cortex
```

**Environment**

* Role version:

    `jesse.quinn@monitoring-security:~/ansible$ ansible-galaxy role list
# /home/jesse.quinn/.ansible/roles
- cloudalchemy.cortex, master
`

* Ansible version information:

    `ansible --version`
    `ansible 2.9.6
  config file = /home/jesse.quinn/ansible/ansible.cfg
  configured module search path = ['/home/jesse.quinn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
`

* Variables:

n/a

* Ansible playbook execution Logs:

```
TASK [cloudalchemy.cortex : Services should be empty when all-in-one-mode is enabled] **************************************************************************************************************************************************
fatal: [cortex]: FAILED! => {
    "assertion": "cortex_all_in_one == (cortex_services|length == 0)",
    "changed": false,
    "evaluated_to": false,
    "msg": "Exactly one of cortex_all_in_one or cortex_services should be set."
}
```

**Comment by lekkalraja** [comment]
Hi, I am also facing the same issue.. so found quick work around for this assertion task as below.
preflight.yml:
  tasks:
  ```yaml
         - name: Services should be empty when all-in-one-mode is enabled
           assert:
              that: cortex_all_in_one == (cortex_services|length == 0)| bool
              msg: "Exactly one of cortex_all_in_one or cortex_services should be set."
           when: cortex_services is defined or (cortex_all_in_one | default(true) == false)
  ```
